#!/bin/sh
# Rebuild the dispatch-split series on top of BASE.
#
# Usage: dispatch-split/replay.sh BASE [BRANCH]
#
# Walks the commits of BRANCH (default: HEAD) since it forked from BASE's
# history.  A commit with a "Generated-by: dispatch-split/<script>" trailer is
# regenerated by running that script on the tree so far; every other commit
# is cherry-picked.  Messages and authorship are kept.  The result is left on
# the branch "dispatch-split-replay".
#
# When BASE is the commit BRANCH was built on, every replayed tree must equal
# the original one, and the script says so: this is how to check that the
# generated commits are exactly what the scripts produce.  On a newer BASE,
# hand-written commits may need conflict resolution like any rebase; the
# script stops in its worktree, printed below, if a cherry-pick fails.
set -eu

base=$(git rev-parse "$1")
branch=$(git rev-parse "${2:-HEAD}")
fork=$(git merge-base "$branch" "$base")

# Run the scripts next to this one, from a copy, so that checking out other
# commits cannot change them midway.
tools=$(mktemp -d)
mkdir "$tools/dispatch-split"
cp "$(dirname "$0")"/*.py "$tools/dispatch-split/"
work=$(mktemp -d)/replay
git worktree add -q --detach "$work" "$base"

check=0
[ "$base" = "$fork" ] && check=1

for c in $(git rev-list --reverse "$fork..$branch"); do
    subject=$(git log -1 --format=%s "$c")
    gen=$(git log -1 --format='%(trailers:key=Generated-by,valueonly)' "$c" | sed -n 's|^dispatch-split/||p')
    if [ -n "$gen" ]; then
        echo "regenerate: $subject  ($gen)"
        python3 "$tools/dispatch-split/$gen" "$work" > /dev/null
        git -C "$work" add -u
        git -C "$work" commit -q -C "$c"
    else
        echo "cherry-pick: $subject"
        if ! git -C "$work" cherry-pick "$c" > /dev/null; then
            echo "cherry-pick failed; resolve it in $work, then rerun from there" >&2
            exit 1
        fi
    fi
    if [ $check = 1 ] && [ "$(git -C "$work" rev-parse HEAD^{tree})" != "$(git rev-parse "$c^{tree}")" ]; then
        echo "  DIFFERS from the original commit:" >&2
        git -C "$work" diff --stat "$c" HEAD >&2
        exit 1
    fi
done

git branch -f dispatch-split-replay "$(git -C "$work" rev-parse HEAD)"
git worktree remove "$work"
rm -rf "$tools"
[ $check = 1 ] && echo "every replayed commit has the same tree as the original"
echo "result: branch dispatch-split-replay"
